class EnvironmentSettings:
    def __init__(self):
        self.workspace_dir = '/home/mbzirc/Downloads/AhsanBB/Dataset_Paper/Codes/CVPR2023/VideoX/SeqTrack/checkpoints'    # Base directory for saving network checkpoints.
        self.tensorboard_dir = '/home/mbzirc/Downloads/AhsanBB/Dataset_Paper/Codes/CVPR2023/VideoX/SeqTrack/tensorboard'    # Directory for tensorboard files.
        self.pretrained_networks = '/home/mbzirc/Downloads/AhsanBB/Dataset_Paper/Codes/CVPR2023/VideoX/SeqTrack/pretrained_networks'
        self.lasot_dir = ''
        self.got10k_dir = '/home/mbzirc/Downloads/AhsanBB/Dataset_Paper/Codes/CVPR2023/VideoX/SeqTrack/DATA2/train'
        self.lasot_lmdb_dir = ''
        self.got10k_lmdb_dir = ''
        self.trackingnet_dir = '/'
        self.trackingnet_lmdb_dir = ''
        self.coco_dir = ''
        self.coco_lmdb_dir = ''
        self.imagenet1k_dir = ''
        self.imagenet22k_dir = ''
        self.lvis_dir = ''
        self.sbd_dir = ''
        self.imagenet_dir = ''
        self.imagenet_lmdb_dir = ''
        self.imagenetdet_dir = ''
        self.ecssd_dir = ''
        self.hkuis_dir = ''
        self.msra10k_dir = ''
        self.davis_dir = ''
        self.youtubevos_dir = ''
